name: Publish new EXE

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller .\AutoupdateRates.exe.spec
      - uses: actions/upload-artifact@v2
        with:
          name: Upload generated EXE
          path: dist/AutoupdateRates.exe
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{  github.ref_name }}
        run: |
          gh release create "${{  github.ref_name }}" dist/AutoupdateRates.exe --repo="$GITHUB_REPOSITORY" --title="${GITHUB_REPOSITORY#*/}" --generate-notes
